export const SEED_JOB_POSTINGS = [
  {
    id: 'JOB20260901',
    name: 'ตามหานักรีวิวบัตรเครดิต KTC PROUD',
    subtitle: 'รีวิวบัตรกดเงินสด KTC PROUD สมัครง่าย อนุมัติไว',
    brief: 'NRI202609058',
    reviewers: 0,
    applicants: 0,
    viewerCount: 0,
    tone: 'mascot',
    brand: 'KTC',
    status: 'Draft',
    owner: 'admin@buddyreview.co',
    platforms: ['Facebook', 'TikTok'],
    followerMin: 10000,
    followerMax: 50000,
    wage: 3500,
    shortBrief:
      'รีวิวบัตรกดเงินสด KTC PROUD ถ่ายทอดประสบการณ์จริงในการสมัครบัตรผ่านแอปพลิเคชัน เน้นความสะดวก รวดเร็ว และสิทธิประโยชน์ที่ได้รับ ทำเป็นคลิปสั้นลง TikTok และแชร์ไปยัง Facebook',
  },
  {
    id: 'JOB20260902',
    name: 'KTC x Agoda สายท่องเที่ยวปลายปี',
    subtitle: 'รีวิวทริปเที่ยวปลายปี พร้อมโปรโมชั่นจองที่พักสุดคุ้มผ่าน Agoda',
    brief: 'NRI202609058',
    reviewers: 20,
    applicants: 150,
    viewerCount: 1500,
    tone: 'mascot',
    brand: 'KTC',
    applyStartDate: '1 ก.ย. 2026',
    deadline: '30 ก.ย. 2026',
    owner: 'marketing@buddyreview.co',
    platforms: ['Instagram', 'Facebook'],
    followerMin: 50000,
    followerMax: 300000,
    wage: 8000,
    shortBrief:
      'สำหรับนักรีวิวสายท่องเที่ยว! ถ่ายภาพบรรยากาศที่พักและการเดินทาง พร้อมไทอินบัตรเครดิต KTC และโปรโมชั่นส่วนลดเมื่อจองที่พักผ่าน Agoda โพสต์รูปภาพ 5-8 รูป พร้อมเขียนบรรยายความประทับใจ',
  },
  {
    id: 'JOB20260903',
    name: 'รีวิวโปรโมชั่น KTC สายกิน (บุฟเฟต์ปิ้งย่าง)',
    subtitle: 'ตะลุยกินร้านบุฟเฟต์ปิ้งย่างชื่อดัง พร้อมส่วนลดพิเศษจาก KTC',
    brief: 'NRI202609058',
    reviewers: 10,
    applicants: 80,
    viewerCount: 800,
    tone: 'mascot',
    brand: 'KTC',
    applyStartDate: '15 ก.ย. 2026',
    deadline: '30 ก.ย. 2026',
    owner: 'content@buddyreview.co',
    platforms: ['TikTok'],
    followerMin: 100000,
    followerMax: 1000000,
    wage: 10000,
    productValue: 1500,
    shortBrief:
      'แคมเปญสายกิน! ถ่ายคลิปวิดีโอสั้นลง TikTok รีวิวร้านบุฟเฟต์ปิ้งย่างที่ร่วมรายการ เน้นภาพอาหารที่น่ากิน บรรยากาศร้าน และตบท้ายด้วยความคุ้มค่าเมื่อจ่ายผ่านบัตรเครดิต KTC',
  },
  {
    id: 'JOB20261001',
    name: 'KTC Cash Card (Batch 1)',
    subtitle: 'รับ Lifestyle Creator ถ่ายทอดการวางแผนค่าใช้จ่ายผ่านวิดีโอสั้น 1 คลิป',
    brief: 'NRI202609058',
    reviewers: 5,
    applicants: 12,
    viewerCount: 120,
    tone: 'mascot',
    brand: 'KTC',
    campaignType: 'normal',
    owner: 'thanya@buddyreview.co',
    targetPost: 5,
    targetGroup:
      'Lifestyle Creator วัยทำงาน เน้นชีวิตประจำวันและการวางแผนค่าใช้จ่าย มีผู้ติดตามชาวไทยเป็นหลัก',
    genders: ['ชาย', 'หญิง'],
    gender: 'ทุกเพศ',
    ageMin: 25,
    ageMax: 40,
    followerMin: 10000,
    followerMax: 100000,
    platforms: ['TikTok', 'Instagram'],
    contentScope: 'Post / Reels',
    contentTypes: ['Post', 'Reels'],
    shortBrief:
      'รับนักรีวิว 5 คน ทำวิดีโอแนวตั้ง 45–60 วินาที คนละ 1 คลิป ลง TikTok หรือ Instagram Reels เล่าแนวทางวางแผนค่าใช้จ่ายและแนะนำ KTC Cash Card ตามข้อมูลที่แบรนด์อนุมัติ โพสต์คลิปพร้อม #KTCCashCard #โฆษณา ห้ามรับรองผลอนุมัติหรือแต่งประสบการณ์ใช้จริง คงโพสต์อย่างน้อย 90 วันและส่งสถิติหลังเผยแพร่ 7 วัน',
    applyStartDate: '2026-10-01',
    deadline: '2026-10-10',
    wage: 4500,
    productValue: 0,
  },
  {
    id: 'JOB20261002',
    name: 'KTC Cash Card (Batch 2)',
    subtitle: 'ตามหานักรีวิววัยทำงาน ถ่ายทอดประสบการณ์ใช้งานบัตร Cash Card',
    brief: 'NRI202609058',
    reviewers: 0,
    applicants: 4,
    viewerCount: 40,
    tone: 'mascot',
    brand: 'KTC',
    applyStartDate: '2 ต.ค. 2026',
    deadline: '12 ต.ค. 2026',
    owner: 'thanya@buddyreview.co',
    platforms: ['Facebook'],
    followerMin: 5000,
    followerMax: 20000,
    wage: 2500,
    shortBrief:
      'ทำคอนเทนต์ประเภท Photo Album ลง Facebook แนะนำวิธีการสมัครและสิทธิประโยชน์ของ KTC Cash Card เหมาะสำหรับพนักงานออฟฟิศที่ต้องการสภาพคล่อง',
  },
  {
    id: 'JOB20261003',
    name: 'KTC Cash Card (Batch 3)',
    subtitle: 'ตามหานักรีวิวสาย Tech แนะนำแอป KTC Mobile',
    brief: 'NRI202609058',
    reviewers: 0,
    applicants: 1,
    viewerCount: 10,
    tone: 'mascot',
    brand: 'KTC',
    applyStartDate: '3 ต.ค. 2026',
    deadline: '15 ต.ค. 2026',
    owner: 'tech@buddyreview.co',
    platforms: ['YouTube'],
    followerMin: 100000,
    followerMax: 500000,
    wage: 20000,
    shortBrief:
      'ทำคลิปวิดีโอ YouTube ความยาว 5-8 นาที รีวิวฟีเจอร์เด่นๆ ในแอป KTC Mobile รวมถึงความง่ายในการจัดการบัตร Cash Card ผ่านแอป',
  },
  {
    id: 'JOB20261004',
    name: 'รีวิวผลิตภัณฑ์ใหม่จาก Boots',
    subtitle: 'ตามหา Beauty Blogger รีวิวครีมบำรุงผิวสูตรใหม่',
    brief: 'NRI202609044',
    reviewers: 10,
    applicants: 45,
    viewerCount: 450,
    tone: 'boots',
    brand: 'Boots',
    applyStartDate: '1 ต.ค. 2026',
    deadline: '15 ต.ค. 2026',
    owner: 'beauty@buddyreview.co',
    platforms: ['Instagram', 'TikTok'],
    followerMin: 20000,
    followerMax: 100000,
    wage: 6000,
    productValue: 2500,
    shortBrief:
      'แคมเปญบิวตี้! ทางแบรนด์จะจัดส่งเซ็ตผลิตภัณฑ์บำรุงผิวสูตรใหม่ไปให้ทดลองใช้ รบกวนรีวิวความรู้สึกหลังใช้และเนื้อสัมผัสของครีม ลงคลิปวิดีโอใน TikTok หรือภาพ Before/After ใน Instagram',
  },
  {
    id: 'JOB20261005',
    name: 'KTC มหกรรมช้อปปิ้งปลายปี',
    subtitle: 'โปรโมทแคมเปญลดหย่อนภาษี ช้อปดีมีคืน',
    brief: 'NRI202609058',
    reviewers: 0,
    applicants: 0,
    viewerCount: 0,
    tone: 'mascot',
    brand: 'KTC',
    applyStartDate: '15 ต.ค. 2026',
    deadline: '31 ต.ค. 2026',
    owner: 'finance@buddyreview.co',
    platforms: ['Facebook'],
    followerMin: 100000,
    followerMax: 1000000,
    wage: 15000,
    shortBrief:
      'อธิบายเงื่อนไขและโปรโมชั่นของ KTC ที่ร่วมกับโครงการลดหย่อนภาษีของรัฐบาล เพื่อกระตุ้นยอดการใช้จ่ายช่วงปลายปี ขอคนที่มีความรู้ด้านการเงินเล็กน้อย อธิบายเข้าใจง่าย',
  },
  {
    id: 'JOB20261101',
    name: 'KTC 11.11 Mega Sale',
    subtitle: 'แคมเปญช้อปปิ้งออนไลน์ที่ใหญ่ที่สุดแห่งปี',
    brief: 'NRI202609058',
    reviewers: 0,
    applicants: 0,
    viewerCount: 0,
    tone: 'mascot',
    brand: 'KTC',
    applyStartDate: '1 พ.ย. 2026',
    deadline: '11 พ.ย. 2026',
    owner: 'marketing@buddyreview.co',
    platforms: ['TikTok', 'Facebook'],
    followerMin: 50000,
    followerMax: 500000,
    wage: 12000,
    shortBrief:
      'รีวิวโปรโมชั่น 11.11 เมื่อช้อปผ่านแพลตฟอร์ม E-Commerce ชื่อดังและชำระด้วยบัตร KTC รับส่วนลดและพอยต์คูณสอง เน้นความตื่นเต้นและกระตุ้นให้อยากช้อป',
  },
];

// Additional prototype announcements for browsing multiple result pages.
SEED_JOB_POSTINGS.push(
  ...Array.from({ length: 24 }, (_, index) => {
    const isDraft = index % 3 === 0;
    const applicants = isDraft ? 0 : (index + 1) * 2;
    return {
      id: `JOB202610${String(101 + index)}`,
      brief: 'NRI202609058',
      name: `KTC Creator — ประกาศตัวอย่าง ${String(index + 1).padStart(2, '0')}`,
      subtitle: ['คอนเทนต์ไลฟ์สไตล์', 'รีวิวสายท่องเที่ยว', 'รีวิวสายกิน'][index % 3],
      brand: 'KTC',
      announcementVersion: 2,
      recruitmentMode: 'manual',
      announcementStatus: index % 3 === 2 ? 'inactive' : 'active',
      status: isDraft ? 'Draft' : 'Published',
      campaignType: 'confidential',
      applicants,
      viewerCount: applicants * 10,
      owner: 'thanya@buddyreview.co',
      platforms: ['TikTok', 'Instagram'],
      followerMin: 10000,
      followerMax: 100000,
      wage: 3500,
      productValue: 0,
      specialCriteriaOptions: ['Travel'],
      shortBrief: 'ข้อมูลตัวอย่างสำหรับทดสอบรายการประกาศและ pagination',
    };
  }),
);
