export const PRELIST_REVIEWERS = [
  {
    id: 1,
    username: 'SP24.7',
    platform: 'instagram',
    followers: 711,
    likes: 61,
    age: 29,
    gender: 'MALE',
    images: [
      'https://picsum.photos/seed/sp1/300/300',
      'https://picsum.photos/seed/sp2/300/300',
      'https://picsum.photos/seed/sp3/300/300',
      'https://picsum.photos/seed/sp4/300/300',
      'https://picsum.photos/seed/sp5/300/300',
      'https://picsum.photos/seed/sp6/300/300',
    ],
    engageLv: 'GOOD',
    reviewed: 1,
    estReach: 307,
    province: 'กรุงเทพมหานคร',
    status: 'Pending',
  },
  {
    id: 2,
    username: 'aommy.style',
    platform: 'tiktok',
    followers: '12K',
    likes: '5.4K',
    age: 24,
    gender: 'FEMALE',
    images: [
      'https://picsum.photos/seed/am1/300/300',
      'https://picsum.photos/seed/am2/300/300',
      'https://picsum.photos/seed/am3/300/300',
      'https://picsum.photos/seed/am4/300/300',
      'https://picsum.photos/seed/am5/300/300',
      'https://picsum.photos/seed/am6/300/300',
    ],
    engageLv: 'EXCELLENT',
    reviewed: 5,
    estReach: '8.2K',
    province: 'เชียงใหม่',
    status: 'Selected',
  },
  {
    id: 3,
    username: 'john_doe_x',
    platform: 'facebook',
    followers: '4.5K',
    likes: 320,
    age: 31,
    gender: 'MALE',
    images: [
      'https://picsum.photos/seed/jd1/300/300',
      'https://picsum.photos/seed/jd2/300/300',
      'https://picsum.photos/seed/jd3/300/300',
      'https://picsum.photos/seed/jd4/300/300',
      'https://picsum.photos/seed/jd5/300/300',
      'https://picsum.photos/seed/jd6/300/300',
    ],
    engageLv: 'AVERAGE',
    reviewed: 0,
    estReach: '1.1K',
    province: 'ภูเก็ต',
    status: 'Rejected',
  },
  {
    id: 4,
    username: 'sweet_cake99',
    platform: 'instagram',
    followers: '52K',
    likes: '12K',
    age: 26,
    gender: 'FEMALE',
    images: [
      'https://picsum.photos/seed/sc1/300/300',
      'https://picsum.photos/seed/sc2/300/300',
      'https://picsum.photos/seed/sc3/300/300',
      'https://picsum.photos/seed/sc4/300/300',
      'https://picsum.photos/seed/sc5/300/300',
      'https://picsum.photos/seed/sc6/300/300',
    ],
    engageLv: 'GOOD',
    reviewed: 12,
    estReach: '25K',
    province: 'กรุงเทพมหานคร',
    status: 'Pending',
  },
];
