export const SEED_PROJECTS = [
  {
    id: 'PRJ2026090022',
    briefNumbers: ['NRI202609058'],
    quote: 'QO2026090022',
    quotations: ['QO2026090022'],
    quotationMetadata: [{ createdAt: '2026-09-28T06:32:00Z', createdBy: 'aareeya@buddyreview.co' }],
    createdAt: '2026-09-28T06:32:00Z',
    createdBy: 'aareeya@buddyreview.co',
    updatedAt: '2026-09-28T07:47:00Z',
    updatedBy: 'nattaya@buddyreview.co',
    name: 'Page Promotion Sale Here',
    owner: 'aareeya@buddyreview.co',
    tone: 'mascot',
    brand: 'Page Promotion',
    status: 'On Going',
    image:
      'https://s3.ap-southeast-1.amazonaws.com/bdb-parse-file/public/project/profile/cbvpbV1FtT-1790576864553.jpg',
  },
  {
    id: 'PRJ2026090021',
    quote: '',
    name: 'Boots Thailand_THE ORDINARY',
    owner: 'prin@buddyreview.co',
    tone: 'boots',
    brand: 'Boots',
    status: 'Draft',
    image: '/assets/boots-ordinary.png',
  },
  {
    id: 'PRJ2026090020',
    quote: '',
    name: 'Makro Detergent',
    owner: 'nilmanee@buddyreview.co',
    tone: 'makro',
    brand: 'Makro',
    status: 'Draft',
    image: '/assets/makro.jpeg',
    target: 30,
    platforms: ['TikTok', 'Instagram'],
  },
  {
    id: 'PRJ2026090017',
    quote: 'QO2026090018',
    name: 'ร้านอาหารสโมสรร',
    owner: 'nilmanee@buddyreview.co',
    tone: 'samosorn',
    brand: 'สโมสร',
    status: 'Complete',
    image: '/assets/samosorn.jpg',
  },
  {
    id: 'PRJ2026090018',
    quote: 'QO2026090019',
    name: 'รสดีแป้งชุบทอด KKR - Hero VDO',
    owner: 'itsariya@buddyreview.co',
    tone: 'rosdee',
    brand: 'รสดี',
    status: 'On Going',
    image: '/assets/rosdee.jpg',
  },
  {
    id: 'PRJ2026090019',
    quote: '',
    name: 'Abbott Ensure Page Promotion',
    owner: 'prin@buddyreview.co',
    tone: 'ensure',
    brand: 'Ensure',
    status: 'Draft',
    image: '/assets/ensure.png',
    target: 15,
    platforms: ['Facebook', 'YouTube'],
  },
  {
    id: 'PRJ2026090016',
    quote: '',
    name: 'PR Beauty Buffet Lucky Fans Event',
    owner: 'aareeya@buddyreview.co',
    tone: 'beauty',
    brand: 'Beauty Buffet',
    status: 'Draft',
    image: '/assets/beauty-buffet.jpg',
  },
  {
    id: 'PRJ2026090015',
    quote: 'QO2026090010',
    name: "Lotus's Cluster Khon Kaen Refresh",
    owner: 'itsariya@buddyreview.co',
    tone: 'lotus',
    brand: "Lotus's",
    status: 'Complete',
    image: '/assets/lotus.jpg',
  },
  {
    id: 'PRJ2026090014',
    quote: '',
    name: 'Boots Thailand_KOL For Review SKY WONGRAVEE Sep',
    owner: 'prin@buddyreview.co',
    tone: 'boots',
    brand: 'Boots',
    status: 'Draft',
    image: '/assets/boots-kol.png',
    target: 20,
    platforms: ['TikTok'],
  },
  {
    id: 'PRJ2026090013',
    quote: '',
    name: "Beauty product review at Clinic_Sep-Dec'26",
    owner: 'itsariya@buddyreview.co',
    tone: 'clinic',
    brand: 'Facetem',
    status: 'Draft',
    image: '/assets/clinic.jpg',
  },
];
