export const CAMPAIGN_INFLUENCERS = [
  {
    id: 'mint',
    name: 'Mint Anda',
    platform: 'Instagram',
    via: ['TikTok'],
    campaignName: 'Summer Skincare Launch',
    campaignPlatforms: ['Instagram', 'TikTok'],
    reviewerType: null,
    status: 'buyer-review',
    campaignCode: null,
  },
  {
    id: 'ohm',
    name: 'Coach Ohm',
    platform: 'YouTube',
    via: ['Instagram'],
    campaignName: 'Home Fitness Gadget',
    campaignPlatforms: ['YouTube', 'Instagram'],
    reviewerType: null,
    status: 'buyer-review',
    campaignCode: null,
  },
  {
    id: 'pp',
    name: 'PP Thanawat',
    platform: 'Instagram',
    via: ['TikTok', 'YouTube'],
    campaignName: 'Luxury Watch Reveal',
    campaignPlatforms: ['Instagram', 'TikTok', 'YouTube'],
    reviewerType: null,
    status: 'buyer-review',
    campaignCode: null,
  },
  {
    id: 'fah',
    name: 'Fah Cafe Review',
    platform: 'Instagram',
    via: [],
    campaignName: 'Cafe Opening Promo',
    campaignPlatforms: ['Instagram'],
    reviewerType: 'Normal',
    status: 'awaiting-confirmation',
    campaignCode: null,
  },
  {
    id: 'boss',
    name: 'Boss Snack Review',
    platform: 'TikTok',
    via: ['Instagram'],
    campaignName: 'Snack Bites Teaser',
    campaignPlatforms: ['TikTok', 'Instagram'],
    reviewerType: 'Normal',
    status: 'confirmed',
    campaignCode: 'A123312B12312312',
  },
];

export const CAMPAIGN_INFLUENCER_STATUSES = [
  { value: 'buyer-review', label: 'รอทีมงานตรวจสอบ', className: 'bg-[#ffecd3] text-[#cf3b00]' },
  {
    value: 'awaiting-confirmation',
    label: 'รอนักรีวิวยืนยัน',
    className: 'bg-[#f0e9ff] text-[#6525ff]',
  },
  { value: 'confirmed', label: 'นักรีวิวยืนยันแล้ว', className: 'bg-[#dcfce7] text-[#12833b]' },
];
